// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMusicFile(arg1) {
  return window['go']['libmanager']['Service']['AddMusicFile'](arg1);
}

export function OpenFileSelector() {
  return window['go']['libmanager']['Service']['OpenFileSelector']();
}

export function SetContext(arg1) {
  return window['go']['libmanager']['Service']['SetContext'](arg1);
}
