// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMusicFolder(arg1) {
  return window['go']['libmanager']['Service']['AddMusicFolder'](arg1);
}

export function GetAllTracks() {
  return window['go']['libmanager']['Service']['GetAllTracks']();
}

export function OpenDirectorySelector() {
  return window['go']['libmanager']['Service']['OpenDirectorySelector']();
}

export function SetContext(arg1) {
  return window['go']['libmanager']['Service']['SetContext'](arg1);
}
