// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {libmanager} from '../models';
import {context} from '../models';

export function AddMusicFolder(arg1:string):Promise<Array<libmanager.Track>>;

export function OpenDirectorySelector():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
